/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import java.awt.Image;
import static java.awt.Image.SCALE_DEFAULT;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.CarDetails;
import model.CarDetailsHistory;
import javax.swing.ImageIcon;


/**
 *
 * @author maverick1997
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    
    CarDetailsHistory history;
    Image image;
   
    public CreateJPanel(CarDetailsHistory history ) {
        initComponents();
        this.history = history;
    }

    CreateJPanel() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitle = new javax.swing.JLabel();
        Brand = new javax.swing.JLabel();
        Model = new javax.swing.JLabel();
        Color = new javax.swing.JLabel();
        year = new javax.swing.JLabel();
        engineNo = new javax.swing.JLabel();
        seats = new javax.swing.JLabel();
        license = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        number = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        License = new javax.swing.JLabel();
        SSN = new javax.swing.JLabel();
        Address = new javax.swing.JLabel();
        ServiceRec = new javax.swing.JLabel();
        Warranty = new javax.swing.JLabel();
        Image = new javax.swing.JLabel();
        txtBrand = new javax.swing.JTextField();
        txtModel = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        txtYear = new javax.swing.JTextField();
        txtEngineNo = new javax.swing.JTextField();
        txtSeats = new javax.swing.JTextField();
        txtLicense = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtNumber = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtDL = new javax.swing.JTextField();
        txtSSN = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtServiceRec = new javax.swing.JTextField();
        txtWarrantyRec = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnAttach = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        lbTitle.setFont(new java.awt.Font("American Typewriter", 3, 18)); // NOI18N
        lbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitle.setText("Create Car Detail");

        Brand.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Brand.setText("Brand");

        Model.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Model.setText("Model");

        Color.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Color.setText("Color");

        year.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        year.setText("Year");

        engineNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        engineNo.setText("Engine No");

        seats.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        seats.setText("Seats No");

        license.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        license.setText("License Plate");

        name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name.setText(" Owner Name");

        number.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        number.setText("Telephone Number");

        Email.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Email.setText("Email Address");

        License.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        License.setText("Driver License");

        SSN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SSN.setText("Social Security Number");

        Address.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Address.setText("Address");

        ServiceRec.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ServiceRec.setText("Service Records");

        Warranty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Warranty.setText("Warranty Records");

        Image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Image.setText("Image");

        txtBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrandActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnAttach.setText("Attach");
        btnAttach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttachActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(year)
                                    .addComponent(Color)
                                    .addComponent(seats)
                                    .addComponent(engineNo)
                                    .addComponent(Address)
                                    .addComponent(Warranty))
                                .addGap(29, 29, 29))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Brand)
                                    .addComponent(Model))
                                .addGap(58, 58, 58)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtBrand, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(txtModel)
                            .addComponent(txtColor)
                            .addComponent(txtYear)
                            .addComponent(txtEngineNo)
                            .addComponent(txtSeats)
                            .addComponent(txtAddress)
                            .addComponent(txtWarrantyRec))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(name)
                                    .addComponent(license)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Email)
                                    .addComponent(License)
                                    .addComponent(SSN)
                                    .addComponent(ServiceRec)
                                    .addComponent(Image)
                                    .addComponent(number))))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAttach)
                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                            .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName)
                            .addComponent(txtLicense, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtServiceRec, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(txtSSN, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtDL, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(197, Short.MAX_VALUE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Address, Color, Email, Image, License, SSN, ServiceRec, Warranty, engineNo, number, seats, year});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Brand, Model, license, name});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbTitle)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Brand)
                    .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(license)
                    .addComponent(txtLicense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Model)
                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Color)
                    .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(number)
                    .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Email)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(year))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(engineNo)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtDL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(License)))
                            .addComponent(txtEngineNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SSN)
                            .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seats))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Address)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ServiceRec)
                            .addComponent(txtServiceRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtWarrantyRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Warranty)
                            .addComponent(Image)
                            .addComponent(btnAttach))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(btnSave)))
                .addContainerGap(440, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Address, Brand, Color, Email, License, Model, SSN, engineNo, name, number, seats, year});

    }// </editor-fold>//GEN-END:initComponents

    private void txtBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrandActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
         //CarDetails cd = history.addNewDetails();
        
//        String address = txtAddress.getText();
//        
//        String brand = txtBrand.getText();
//        String model = txtModel.getText();
//        String color = txtColor.getText();
//        
//        String engineNo = txtEngineNo.getText();
//        String plates = txtLicense.getText();
//        
//        String Email =txtEmail.getText();
//        String ownerID = txtDL.getText();
//        String PhoneNumber =  txtNumber.getText();
//        String ServiceRecords = txtServiceRec.getText();
//        
//        String Name = txtName.getText();
       try{ 
           String address = txtAddress.getText();
      int seats= Integer.parseInt(txtSeats.getText());
        String WarrantyYears = txtWarrantyRec.getText();
        String brand = txtBrand.getText();
        String model = txtModel.getText();
        String color = txtColor.getText();
        
        String engineNo = txtEngineNo.getText();
        String plates = txtLicense.getText();
        
        String Email =txtEmail.getText();
        String ownerID = txtDL.getText();
        String PhoneNumber =  txtNumber.getText();
        String ServiceRecords = txtServiceRec.getText();
        String SSN = txtSSN.getText();
        String Name = txtName.getText();
        
        String date = txtYear.getText();
        if(brand.trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Car Brand is Empty!");
         txtBrand.grabFocus();
            return;
         
        }
        else if(model.trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Car Model is Empty!");
         txtModel.grabFocus();
            return;
        }else if(color.trim().isEmpty()){
            
         JOptionPane.showMessageDialog(this, "Car color is Empty!");
         txtColor.grabFocus();
            return;
        }else if(engineNo.trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Car EngineNo is Empty!");
         txtEngineNo.grabFocus();
            return;
        }else if(plates.trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Car License Plate is Empty!");
         txtLicense.grabFocus();
            return;
          }else if(Name.trim().isEmpty()){
              JOptionPane.showMessageDialog(this, "Owner Name is Empty!");
         txtName.grabFocus();
            return;
          }else if(Email.trim().isEmpty()){
              JOptionPane.showMessageDialog(this, "Email Address is Empty!");
         txtEmail.grabFocus();
            return;
          }else if(ownerID.trim().isEmpty()){
              JOptionPane.showMessageDialog(this, "Driver License is Empty!");
         txtDL.grabFocus();
            return;
          }else if(address.trim().isEmpty()){
              JOptionPane.showMessageDialog(this, "Adddress is Empty!");
         txtAddress.grabFocus();
            return;
          }else if(ServiceRecords.trim().isEmpty()){
              JOptionPane.showMessageDialog(this, "ServiceRecord is Empty!");
         txtServiceRec.grabFocus();
            return;
          }else if(PhoneNumber.trim().isEmpty()){
           JOptionPane.showMessageDialog(this, "Phone Number  is Empty!");
         txtNumber.grabFocus();
            return;
          }else if(String.valueOf(PhoneNumber).length() != 10){
              JOptionPane.showMessageDialog(this, "Input Valid Telephone Number !");
                        txtNumber.grabFocus();
                        return;
          }else if(String.valueOf(date).length()!=4){
               JOptionPane.showMessageDialog(this, "Input Valid Year !");
                       txtYear.grabFocus();
                        return;
          }else if(String.valueOf(SSN).length()!=9){
                JOptionPane.showMessageDialog(this, "Input Valid SSN !");
                       txtSSN.grabFocus();
                       return;
          }else if(String.valueOf(WarrantyYears).length() != 4){
              
          JOptionPane.showMessageDialog(this, "Input Valid Warranty Year !");
                       txtWarrantyRec.grabFocus();
                       return;
          }
          else{
                  
              CarDetails cd = history.addNewDetails();
             
              cd.setBrand(brand);
              cd.setPhoneNumber(PhoneNumber);
              cd.setColor(color);
              cd.setAddress(address);
              cd.setEmail(Email);
              cd.setEngineNo(engineNo);
              cd.setModel(model);
              cd.setName(Name);
              cd.setOwnerID(ownerID);
              cd.setPlates(plates);
              cd.setServiceRecords(ServiceRecords);
              cd.setPhoto(image);
              cd.setDate(date);
              cd.setSSN(SSN);
              cd.setWarrantyYears(WarrantyYears);
               cd.setSeats(seats);
          }
       }catch(NumberFormatException e){
           JOptionPane.showMessageDialog(this, "Put proper Number in Total Seats !");
            txtSeats.grabFocus();
            return;
        }
//        try{
//            int seats= Integer.parseInt(txtSeats.getText());
//            cd.setSeats(seats);
//        }
//        catch(NumberFormatException e)
//        {JOptionPane.showMessageDialog(this, "Put proper Number in Total Seats !");
//            txtSeats.grabFocus();
//            return;
//        }
//        
//        try{
//            
//                        if (String.valueOf(PhoneNumber).length() != 10)
//                    {
//                        JOptionPane.showMessageDialog(this, "Input Valid Telephone Number !");
//                        txtNumber.grabFocus();
//                        return;
//                        
//                    }
//                        cd.setPhoneNumber(PhoneNumber);
//
//        }catch(NumberFormatException e)
//        {JOptionPane.showMessageDialog(this, "Input Valid Telephone Number !");
//            txtNumber.grabFocus();
//            return;
//        }  
//        
//        try{
//            String date = txtYear.getText();
//            if (String.valueOf(date).length()!=4){
//                JOptionPane.showMessageDialog(this, "Input Valid Year !");
//                        txtYear.grabFocus();
//                        return;
//            }
//            cd.setDate(date);
//        }catch(NumberFormatException e)
//        {JOptionPane.showMessageDialog(this, "Input Valid Year !");
//            txtYear.grabFocus();
//            return;
//        }
//        
//        try{
//            String SSN = txtSSN.getText();
//            if(String.valueOf(SSN).length()!=9){
//                JOptionPane.showMessageDialog(this, "Input Valid SSN !");
//                        txtSSN.grabFocus();
//                        return;
//
//            }
//            cd.setSSN(SSN);
//               
//        } catch(NumberFormatException e)
//        {JOptionPane.showMessageDialog(this, "Input Valid SSN !");
//            txtSSN.grabFocus();
//            return;
//        } 
//       try{
//           String WarrantyYears = txtWarrantyRec.getText();
//           if(String.valueOf(WarrantyYears).length() != 4)
//         {
//         } else {
//               JOptionPane.showMessageDialog(this, "Input Valid Warranty Year !");
//               txtWarrantyRec.grabFocus();
//               return;
//             }
//         cd.setWarrantyYears(WarrantyYears);
//    }catch(NumberFormatException e)
//        {JOptionPane.showMessageDialog(this, "Input Valid Warranty Year !");
//            txtWarrantyRec.grabFocus();
//            return;
//        } 
//
//        
//        
//        
//        
//   
//        
//      
//        
//        
//       
//        cd.setPhoto(image);
               
        JOptionPane.showMessageDialog(this, "New Car Details have been Added");
        
        txtAddress.setText("");
        txtSeats.setText("");
        txtBrand.setText("");
        txtColor.setText("");
        txtDL.setText("");
        txtEmail.setText("");
        txtEngineNo.setText("");
        txtLicense.setText("");
        txtModel.setText("");
        txtName.setText("");
        txtSSN.setText("");
        txtSeats.setText("");
        txtServiceRec.setText("");
        txtWarrantyRec.setText("");
        txtYear.setText("");
        txtNumber.setText("");
       
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnAttachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttachActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();;
        int showOpenDialogue = chooser.showOpenDialog(null);
        
        if(showOpenDialogue == JFileChooser.APPROVE_OPTION){
            File selectedImageFile = chooser.getSelectedFile();
            ImageIcon a = new ImageIcon(selectedImageFile.toString());
            image = a.getImage().getScaledInstance(jLabel1.getWidth(),jLabel1.getHeight(), SCALE_DEFAULT);
            
            jLabel1.setIcon(new ImageIcon(image));
            JOptionPane.showMessageDialog(this, "Image Uploaded");
            //cd.setPhoto(image);
        }
        System.out.println("avc");
      /*JFileChooser j = new JFileChooser();
        int r = j.showSaveDialog(null);
        if(r == JFileChooser.APPROVE_OPTION){
            
            ImageIcon photo = new ImageIcon(new ImageIcon(j.getSelectedFile().getAbsolutePath()).getImage().getScaledInstance(200, 200, SCALE_DEFAULT));
            jLabel1.setIcon(photo);
            CarDetails.setPhoto(photo);
           
        } */
          
    }//GEN-LAST:event_btnAttachActionPerformed
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address;
    private javax.swing.JLabel Brand;
    private javax.swing.JLabel Color;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Image;
    private javax.swing.JLabel License;
    private javax.swing.JLabel Model;
    private javax.swing.JLabel SSN;
    private javax.swing.JLabel ServiceRec;
    private javax.swing.JLabel Warranty;
    private javax.swing.JButton btnAttach;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel engineNo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JLabel license;
    private javax.swing.JLabel name;
    private javax.swing.JLabel number;
    private javax.swing.JLabel seats;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtDL;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEngineNo;
    private javax.swing.JTextField txtLicense;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNumber;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtSeats;
    private javax.swing.JTextField txtServiceRec;
    private javax.swing.JTextField txtWarrantyRec;
    private javax.swing.JTextField txtYear;
    private javax.swing.JLabel year;
    // End of variables declaration//GEN-END:variables
}
